CREATE TABLE TOTAL_VISUALIZACOES_POR_SEMANA(
	NM_CANAL string,
	ID_VIDEO string,
	TITULO_VIDEO string,
	TOTAL_CARACTERE_VIDEO INT,
	TAGS ARRAY<string>,
	DURACAO_VIDEO_MINUTOS FLOAT,
	TOTAL_TAGS INT,
	TOTAL_VISUALIZACOES INT,
	TOTAL_COMENTARIOS INT,
	TOTAL_LIKES INT,
	TOTAL_VISUALIZACOES_DIA INT, 
	TOTAL_COMENTARIOS_DIA INT,
	TOTAL_LIKES_DIA INT,
	data_extracao DATE,
	ID_CANAL STRING
) 
PARTITIONED BY()
STORED AS PARQUET
LOCATION 'hdfs://projeto/youtube_datalake/total_video_publicado_semana.parquet';


-------------------------TESTE CRIACAO TABELA PARTICINADA------------------------------

CREATE EXTERNAL TABLE IF NOT EXISTS TOTAL_VIDEO_PUBLICADO_SEMANA_TESTE (
    SEMANA_TRADUZIDA STRING,
    NM_CANAL STRING,
    TOTAL_VIDEOS INT
)
PARTITIONED BY (DATA_PUBLICACAO DATE, ID_CANAL STRING)
STORED AS PARQUET
LOCATION 'hdfs://localhost:9000/projeto/teste/teste.parquet';

LOAD DATA INPATH 'hdfs://localhost:9000/projeto/teste/teste.parquet' INTO TABLE TOTAL_VIDEO_PUBLICADO_SEMANA_TESTE;



ALTER TABLE TOTAL_VIDEO_PUBLICADO_SEMANA_TESTE ADD PARTITION (DATA_PUBLICACAO='2023-10-15', ID_CANAL='UC1mk6EtfMjxR4eEZ7C43zTQ') 
LOCATION 'hdfs://localhost:9000/projeto/youtube_datalake/total_video_publicado_semana.parquet/DATA_PUBLICACAO=2023-10-15/ID_CANAL=UC1mk6EtfMjxR4eEZ7C43zTQ';


set hive.exec.dynamic.partition.mode;

-------

CREATE EXTERNAL TABLE IF NOT EXISTS TOTAL_VIDEO_PUBLICADO_SEMANA (
    SEMANA_TRADUZIDA STRING,
    NM_CANAL STRING,
    TOTAL_VIDEOS INT, DATA_PUBLICACAO DATE, ID_CANAL STRING
)
STORED AS PARQUET
LOCATION 'hdfs://localhost:9000/projeto/teste/teste.parquet';


DESCRIBE TOTAL_VIDEO_PUBLICADO_SEMANA_TESTE;

SELECT * FROM TOTAL_VIDEO_PUBLICADO_SEMANA_TESTE
where id_canal  = 'UCrOH1V-FyMunBIMrKL0y0xQ';

SHOW PARTITIONS TOTAL_VIDEO_PUBLICADO_SEMANA_TESTE;
